Vectorizing - How it is better than explicit For Loops. 

In [9]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("Vectorized")
print(1000*(toc - tic))

tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print(1000*(toc - tic))

Vectorized
2.5031566619873047
1139.2598152160645


Broadcasting in Python

In [17]:
import numpy as np

A = np.array([[56.0 ,0.0 ,4.4, 68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0 ,0.9]])
print(A)



[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [18]:
cal = np.sum(A,axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [19]:
perc = 100 * A / cal.reshape(1,4)
print(perc)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [28]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)
c = a * b
print(c)

[[-0.3959935   1.03234353  0.19385067]
 [ 1.60989085  3.54402772  2.38272456]
 [ 0.00698673  0.00528151  0.01459153]]


In [29]:
a = np.random.randn(2,3)
b = np.random.randn(2,1)
c = a + b
print(c)

[[ 2.2380291   2.84711088  2.06094277]
 [-1.01112323  1.57169599  0.52962129]]
